### ISSUE TITLE
Misinterprets Non-Craftable with simple item varient.

### ISSUE THREAD

**Issue by Hexenum** [TryHardDo/EasyCopyPaste#1]
![image](https://github.com/TryHardDo/EasyCopyPaste/assets/94901586/55381fce-358d-4739-8c3a-553c27cb9b06)

**Comment by TryHardDo** [comment]
Also offers all possible items while asking for simple ks items. Example: Killstreak Scattergun you will receive the list if you have it in stock with strange, profks and the rest combinations.

**Comment by TryHardDo** [comment]
Duplicate of #2
