### ISSUE TITLE
Replaces "_" with empty space in remove command 

### ISSUE THREAD

**Issue by Hexenum** [TryHardDo/EasyCopyPaste#3]
![image](https://github.com/TryHardDo/EasyCopyPaste/assets/94901586/7c893326-4288-4982-ad04-92fda4738776)

**Comment by TryHardDo** [comment]
Issues is related to the implementation code inside autobot sources.
The tracking of the fix appear [HERE](https://github.com/TF2Autobot/tf2autobot/compare/master...TryHardDo:tf2autobot:easy-copy-paste-implementation)

**Comment by TryHardDo** [comment]
Fixed with commit: https://github.com/TF2Autobot/tf2autobot/commit/ca4b2c39207ec29ed4b65b7a33f5d3788670fdab
